// <auto-generated />
using FindBeeNumbers.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CheckNumberPhone.Core.Migrations
{
    [DbContext(typeof(PhoneContext))]
    [Migration("20210824070722_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FindBeeNumbers.Core.Entities.Phone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Network")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Network");

                    b.Property<string>("Number")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Number");

                    b.HasKey("Id");

                    b.ToTable("Phones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Network = "Viettel",
                            Number = "0861975619"
                        },
                        new
                        {
                            Id = 2,
                            Network = "Viettel",
                            Number = "0975375619"
                        },
                        new
                        {
                            Id = 3,
                            Network = "Mobi",
                            Number = "0894375619"
                        },
                        new
                        {
                            Id = 4,
                            Network = "VinaPhone",
                            Number = "0917775619"
                        },
                        new
                        {
                            Id = 5,
                            Network = "Viettel",
                            Number = "0337578949"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
